name: Renovate

on:
    push:
        branches:
          - "main"

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install Dependencies
        run: |
            sed -i "s/\${TOKEN_FOR_GITHUB}/${{ secrets.PRIVATE_NPM_TOKEN }}/g" .npmrc
            cat .npmrc
            npm install

      - name: Run Renovate
        env:
          PRIVATE_NPM_TOKEN: ${{ secrets.PRIVATE_NPM_TOKEN }}
        run: npx renovate
